### ISSUE TITLE
Documentation needs information on Secrets

### ISSUE THREAD

**Issue by Hounddog** [UKHomeOffice/jenkins-docker-aws#8]
The documentation is missing some information how to use Kubernetes secrets instead of AWS KMS

**Comment by timgent** [comment]
Hi @Hounddog - I've made some updates and a new pull request. Could you let me know if this works for you and if it is what you were looking for? Thanks
https://github.com/UKHomeOffice/jenkins-docker-aws/pull/9

**Comment by Hounddog** [comment]
@timgent Yes, this is the docs i was looking for to map the configs into the docker via kubernetes secret.

**Comment by timgent** [comment]
Good stuff, I'll close this issue
